# Generated by Django 4.2.19 on 2025-05-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
        ('nautobot_bgp_models', '0010_alter_autonomoussystem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_asns', to='ipam.vrf'),
        ),
        migrations.AlterField(
            model_name='autonomoussystemrange',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_asn_ranges', to='ipam.vrf'),
        ),
    ]
