# Generated by Django 4.2.19 on 2025-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_bgp_models', '0011_autonomoussystem_vrf_alter_autonomoussystemrange_vrf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='autonomoussystem',
            constraint=models.UniqueConstraint(fields=('asn', 'vrf'), name='unique_asn_per_vrf'),
        ),
        migrations.AddConstraint(
            model_name='autonomoussystemrange',
            constraint=models.UniqueConstraint(fields=('asn_min', 'asn_max', 'vrf'), name='unique_asrange_per_vrf'),
        ),
    ]
