# Generated by Django 4.2.19 on 2025-05-20 12:50

from django.db import migrations
import nautobot.dcim.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_bgp_models', '0012_autonomoussystem_unique_asn_per_vrf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomoussystem',
            name='asn',
            field=nautobot.dcim.fields.ASNField(),
        ),
    ]
