# Generated by Django 4.2.19 on 2025-05-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
        ('nautobot_bgp_models', '0013_alter_autonomoussystem_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerendpoint',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_peers', to='ipam.vrf'),
        ),
    ]
